[package]
name = "circles_nofi_clip_tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arboard = "3.4.0"
clap = { version = "4.5.16", features = ["derive", "string"] }
image = "0.25.2"
